package com.smallworldfs.moneytransferapp.base.presentation.viewmodel

enum class Success {
    ON_BOARDING_ACTIVITY,
    WELCOME_ACTIVITY,
    LOGIN_ACTIVITY,
    PASS_CODE_ACTIVITY,
    SMS_VERIFICATION_ACTIVITY,
    APP_CUSTOMIZATION_ACTIVITY,
    FREE_USER_REGISTRATION_ACTIVITY,
    FORGOT_PASSWORD_ACTIVITY,
    RESET_PASSWORD_ACTIVITY,
    HOME_ACTIVITY,
    CHANGE_PASSWORD_ACTIVITY,
    SHOW_TERMS_AND_CONDITIONS,
    PASSWORD_CHANGED,
    INTENT_ERROR,
    CONTACT_SUPPORT_INFO_RECEIVED,
    RECEIVE_CALL,
    CALL_US,
    LIVEZILLA_ACTIVITY,
    SWWEBVIEW_ACTIVITY,
    SEND_EMAIL_ACTIVITY,
    SEND_EMAIL_LIMITED_USER_ACTIVITY,
    MARKETING_PREFERENCES_SAVED,
    UNKNOWN_ACTIVITY
}
