package com.smallworldfs.moneytransferapp.domain.migrated.base

import com.smallworldfs.moneytransferapp.utils.STRING_EMPTY

sealed class Error(val message: String) {
    class UncompletedOperation(message: String = "") : Error(message)
    class OperationCompletedWithError(message: String = "") : Error(message)
    class Unauthorized(message: String = "") : Error(message)
    class Unmapped(message: String = "") : Error(message)
    class UnsupportedOperation(message: String = "") : Error(message)
    class ConnectionError(message: String = "") : Error(message)
    class UnregisteredUser(message: String = "") : Error(message)
    class PendingPhoneValidation(message: String = "") : Error(message)
    class PendingProfileValidation(message: String = "") : Error(message)
    class BiometricAuthenticationFail(message: String = "") : Error(message)
    class SaveDataError(message: String = "") : Error(message)
    class ReadDataError(message: String = "") : Error(message)
    class DeleteDataError(message: String = "") : Error(message)
    class EntityValidationError(message: String = "", val fields: List<FieldError>) : Error(message)
    class UserAlreadyRegistered(message: String = "") : Error(message)
    class LoginCredentials(message: String = "") : Error(message)
    class UserNotAvailable(message: String = "") : Error(message)
    class InvalidPhoneCode(message: String = "") : Error(message)
    class EmailScoreNotPassed(message: String = "") : Error(message)
    class StateBlocked(message: String = "") : Error(message)
    class UserNotAvailableForTransactions(message: String = "") : Error(message)
    class NoUserInDataBase(message: String = "") : Error(message)
    class UserStatusNotPdtProfileForHardRegister(message: String = "") : Error(message)
    class NameIncorrectLength(message: String = "") : Error(message)
    class PasswordIncorrectLength(message: String = "") : Error(message)
    class EmailIncorrectLength(message: String = "") : Error(message)
    class EmailFieldNotValidType(message: String = "") : Error(message)
    class IncorrectCredentials(message: String = "") : Error(message)
    class AddressNotFound(message: String = "") : Error(message)
    class OTPNotFound(message: String = "") : Error(message)
    class SecurityErrorForbidden(message: String = "") : Error(message)
    class SecurityErrorInvalidIntegrity(message: String = "") : Error(message)
    class UpdateRequired(message: String = "") : Error(message)
    class LocationUnavailable(message: String = "") : Error(message)
    class BrazeUserNotFund(message: String = "") : Error(message)
    class UnableToEncodeFile(message: String = "") : Error(message)
    class ValidationPending(message: String = "") : Error(message)
    class DocumentNotFound(message: String = "") : Error(message)
    object PromotionNotExists : Error(STRING_EMPTY)
}

class FieldError(val field: String, val error: List<String>)
